name: on-push-publish-to-npm
on:
  push:
    branches:
      - main
    paths:
      - "package.json"
jobs:
  publish:
    uses: adobe/aio-reusable-workflows/.github/workflows/on-push-publish-to-npm.yml@main
    secrets: inherit